### ISSUE TITLE
feat: Runtime toggle

### ISSUE THREAD

**Issue by alexcroox** [capacitor-community/privacy-screen#13]
**Describe the solution you'd like**
Thank you for your work on this plugin. 

This may not be possible due to a OS/framework level limitation but is it possible to toggle privacy mode at runtime?

For example if the user is on a financials screen I would enable it but on other pages I’d disable it. 

Not an issue if not possible, just curious.

**Comment by robingenz** [comment]
Thanks for the feature request.
This should be possible.

**Comment by alexcroox** [comment]
Amazing thank you!
