### ISSUE TITLE
feat: use splash screen

### ISSUE THREAD

**Issue by robingenz** [capacitor-community/privacy-screen#27]
**Is your feature request related to a problem? Please describe.**
Currently a gray screen is displayed. It would be nice to show the splash screen of the app instead.

**Describe the solution you'd like**
Show the splash screen of the app instead of a gray screen.
The implementation of the Capacitor SplashScreen plugin should be used if possible.

**Describe alternatives you've considered**
No alternative solutions.

**Comment by robingenz** [comment]
@doatech Currently not.

**Comment by UlricW** [comment]
Hi,
Any chance to get it ?

**Comment by robingenz** [comment]
Unfortunately I have too many todos at the moment. But PRs are welcome.

**Comment by robingenz** [comment]
This feature is now available in version 4.2.0 thanks to @UlricW.

Closed by #66
