### ISSUE TITLE
feat: Is it possible to customize the Toast Text?

### ISSUE THREAD

**Issue by FaizIkhwan** [capacitor-community/privacy-screen#39]
Currently when I screenshot, it will display "Can't take screenshot due to security policy."

Is it possible to make the text custom?

I have check the documentation, it seems not possible.

**Comment by robingenz** [comment]
Hi @FaizIkhwan,
thank you for your request.
I just did a quick research and didn't find anything. So it seems that it is not possible. For this reason I close the issue. 
If someone knows a way to do this, please let me know.
