### ISSUE TITLE
bug: inappbrowser visible

### ISSUE THREAD

**Issue by danielehrhardt** [capacitor-community/privacy-screen#42]
**Plugin version:**

**Platform(s):**

**Current behavior:**

When you show the inappbrowser and minimize the app the inapp browser is still visible.
https://www.npmjs.com/package/cordova-plugin-inappbrowser

**Expected behavior:**

the inappbrowser should not be visible

**Steps to reproduce:**

install inappbrowser show a window and then move the app to the background 

**Related code:**

```
insert short code snippets here
```

**Other information:**

iOS

**Capacitor doctor:**

```
insert the output from `npx cap doctor` here
```

**Comment by KerimM** [comment]
There is any workaround or fix?
