### ISSUE TITLE
bug: Pixel 5 not firing

### ISSUE THREAD

**Issue by danielehrhardt** [capacitor-community/privacy-screen#43]
**Plugin version:**

2.1.1

**Platform(s):**
Android Pixel 5 API 32
You can use the Android Simulator to reproduce.
![image](https://user-images.githubusercontent.com/19570043/167299244-1cbaa550-9da3-41cd-90a2-d6b3be22b2ce.png)

**Current behavior:**
Should fire when the App go into pause.
On other Android Phones this fires when i press the square on Android or when i move the App up to see all open Apps.

**Expected behavior:**
The Privacy Screen should fire when you move the App up hold 1-2 Seconds to see the open Apps.

**Steps to reproduce:**
Move the App up hold 1-2 Seconds to see the open Apps.

**Comment by robingenz** [comment]
Hi @danielehrhardt,
i cannot reproduce the problem:

![grafik](https://user-images.githubusercontent.com/13857929/167479762-a02e6372-6dc1-44c9-b9a3-341b7ba7d1fa.png)

If you look in the code you will see that I am just setting a simple flag. Maybe the behavior has changed with API 32. But there is nothing I can do about that.

**Comment by robingenz** [comment]
I close the issue due to inactivity.
