### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Chamiyalt** [capacitor-community/privacy-screen#46]
**Plugin version:**
@capacitor-community/privacy-screen": "^3.0.1

**Platform(s):**
android-

**Current behavior:**
Build faild

**Expected behavior:**
should be build without errors

**Steps to reproduce:**
I have installed the plugin and implenet  the plugin in  app.component.ts file two build error have been thrown 
how can i solve this ?

**Related code:**

ERROR in node_modules/@capacitor-community/privacy-screen/dist/esm/index.d.ts:1:13 - error TS1005: '=' expected.
node_modules/@capacitor-community/privacy-screen/dist/esm/index.d.ts:1:42 - error TS1005: ';' expected.

**Comment by robingenz** [comment]
Hi @Chamiyalt,
thank you for your request.
Please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) so I can debug the issue.

**Comment by Chamiyalt** [comment]
in the definitions.d.ts file
declare module '**@capacitor/cli**' 
@capacitor/cli gives  the  error 
Invalid module name in augmentation. Module '@capacitor/cli' resolves to an untyped module at 'c:/Mob 1/node_modules/@capacitor/cli/dist/index.js', which cannot be augmented.ts(2665)
