### ISSUE TITLE
bug: Not working on ios

### ISSUE THREAD

**Issue by JayKhot** [capacitor-community/privacy-screen#49]
**Plugin version:**

we are using Version 2.1.1   we have disabled screenshot but still we can take sceenshot on ios

**Platform(s):**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Capacitor doctor:**

```
insert the output from `npx cap doctor` here
```

**Comment by robingenz** [comment]
See `README.md`:

> On Android, this plugin sets the FLAG_SECURE flag to treat the content of the window as secure, preventing it from appearing in screenshots or from being viewed on non-secure displays.
On iOS, this plugin hides the webview window when the app is no longer active and loses focus (UIApplicationWillResignActiveNotification) so that a gray screen is shown instead.

Screenshot prevention is only supported on Android.
