### ISSUE TITLE
bug: privacy screen plugin breaks permission handling of @capacitor/camera

### ISSUE THREAD

**Issue by adamk22** [capacitor-community/privacy-screen#50]
**Plugin version:**
"@capacitor-community/privacy-screen": "^3.0.1",

**Platform(s):**
iOS

**Current behavior:**
Using the official camera plugin:

```
"@capacitor/camera": "4.1.4",
```

It will break the usual permission handling when the privacy-screen plugin. Occasionally it will show a grey background and make the app unusable when selecting the "Select Photo's..." option of the iOS photo roll permission options. 

After a lot of trial and error, I found out that privacy-screen was the plugin that caused the conflict. 

**Expected behavior:**
That it wont break the permission handling of the official capacitor camera plugin.

**Steps to reproduce:**
1. Create a new ionic app
2. Install the privacy-screen and camera plugin
3. Add related code to the home screen (with relevant buttons to toggle the functions)
4. When `camera()` is picked, I expect the camera to show up after the accepting permission, instead it just disappears and does nothing. You have to toggle the camera again to make it popup again.
5. When `gallery()` is picked, I expect the photoroll to show up after accepting either choices. If you allow all, it disappears and does nothing. If you allow selected photos it will eiher disappear or it will show the photo roll for a second and will remain in a stuck state with a grey background. 

**Related code:**

```
  async camera() {
    const image = await Camera.getPhoto({
      quality: 90,
      allowEditing: false,
      source: CameraSource.Camera,
      resultType: CameraResultType.Uri,
    });

    console.log(image);
  }

  async gallery() {
    const image = await Camera.getPhoto({
      quality: 90,
      allowEditing: false,
      source: CameraSource.Photos,
      resultType: CameraResultType.Uri,
    });

    console.log(image);
  }
```

**Other information:**
```
    "@capacitor/android": "4.7.0",
    "@capacitor/app": "4.1.1",
    "@capacitor/camera": "4.1.4",
    "@capacitor/core": "4.7.0",
    "@capacitor/device": "4.1.0",
    "@capacitor/haptics": "4.1.0",
    "@capacitor/ios": "4.7.0",
    "@capacitor/keyboard": "4.1.1",
    "@capacitor/preferences": "4.0.2",
    "@capacitor/push-notifications": "4.1.2",
    "@capacitor/splash-screen": "4.1.2",
    "@capacitor/status-bar": "^4.1.1",
```

**Capacitor doctor:**

```
Latest Dependencies:

  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/android: 4.7.0
  @capacitor/ios: 4.7.0

Installed Dependencies:

  @capacitor/android: 4.7.0
  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/ios: 4.7.0

```

**Comment by robingenz** [comment]
Thank you for your request.
Please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) in a public GitHub repository so I can debug the issue.

**Comment by adamk22** [comment]
Sure, I have a repo right here: https://github.com/adamk22/privacy-screen-bug

**Comment by robingenz** [comment]
I don't have a quick fix right now but you can use this workaround: 

```diff
async camera() {
+    await PrivacyScreen.disable();
    const image = await Camera.getPhoto({
      quality: 90,
      allowEditing: false,
      source: CameraSource.Camera,
      resultType: CameraResultType.Uri,
    });
+    await PrivacyScreen.enable();

    console.log(image);
  }
```

You can't see anything from the app in the app switcher anyway because the camera/gallery is open.

**Comment by qliqdev** [comment]
Trying to figure out why disabling PrivacyScreen not helps with [BarcodeScanner](https://www.npmjs.com/package/@capacitor-community/barcode-scanner)

Example:

```
import { BarcodeScanner, ScanOptions, SupportedFormat } from '@capacitor-community/barcode-scanner';
import { ScanResult } from '@capacitor-community/barcode-scanner/dist/esm/definitions';
import { PrivacyScreen } from '@capacitor-community/privacy-screen';

async scan(options: ScanOptions): Promise<ScanResult> {
    await PrivacyScreen.disable();
    const result = await BarcodeScanner.startScan(opts.options);
    console.log(result);
    await BarcodeScanner.stopScan();
    await PrivacyScreen.enable();
}
```

anyway black screen with opened Keyboard appears.

If you tap to screen once, Keyboard disappears and then you can view camera stream as normally.

May be there is a way to blur (focus out) from `SecureTextEntry`?
or we can remove all layers of secure text field?

**Comment by qliqdev** [comment]
https://github.com/capacitor-community/privacy-screen/blob/6d5d233fd20c13ba9138848b068de12f15645ddd/ios/Plugin/PrivacyScreen.swift#L79-L82

Why there is twice call of addSecureText?

**Comment by robingenz** [comment]
@qliqdev See https://github.com/capacitor-community/privacy-screen/issues/64#issuecomment-1711775384

**Comment by robingenz** [comment]
Does the problem still exist with the latest version?
