### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by robiulhassanshakil** [capacitor-community/privacy-screen#53]
**Plugin version:**

    "@capacitor-community/privacy-screen": "^3.0.1",

**Platform(s):**

   android

**Current behavior:**

i am geting build error 
```
[capacitor] × Running Gradle build - failed!
[capacitor] [error] 
[capacitor]         FAILURE: Build failed with an exception.
[capacitor]
[capacitor]         * Where:
[capacitor]         Settings file 'D:\Ionic\photo-gallery\android\settings.gradle' line: 5
[capacitor]
[capacitor]         * What went wrong:
[capacitor]         A problem occurred evaluating settings 'android'.
[capacitor]         > Could not open dsl generic class cache for script 'D:\Ionic\photo-gallery\android\capacitor.settings.gradle' (C:\Users\User\.gradle\caches\7.4.2\scripts\apwscly1yusq2v99tlrgbl2m0).
[capacitor]         > BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63
[capacitor]
[capacitor]         * Try:
[capacitor]         > Run with --stacktrace option to get the stack trace.
[capacitor]         > Run with --info or --debug option to get more log output.
[capacitor]         > Run with --scan to get full insights.
[capacitor]
[capacitor]         * Get more help at https://help.gradle.org
[capacitor]
[capacitor]         BUILD FAILED in 713ms
```

**Expected behavior:**

**Steps to reproduce:**

install the npm,then add plugin in capacitor.config.ts

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Capacitor doctor:**

```
insert the output from `npx cap doctor` here
```

**Comment by robingenz** [comment]
Thank you for your request.
Please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) in a public GitHub repository so I can debug the issue.

**Comment by robingenz** [comment]
Thank you!

I tested it and was able to build your project without any problems. Unfortunately, I can't reproduce the problem. Please clone everything again, make sure you have the latest Android Studio version and try again.

![grafik](https://user-images.githubusercontent.com/13857929/227189911-59b1d31b-8b6d-4c3e-b207-3e263662f386.png)

**Comment by robiulhassanshakil** [comment]
Thank you so much. The problem is from my side.
