### ISSUE TITLE
Question:  Is it correct to allow taking a screenshot on iOS?

### ISSUE THREAD

**Issue by andrerds** [capacitor-community/privacy-screen#58]
**Plugin version:**

version "^5.0.0"
**Platform(s):**

IOS 16.4.1 - Device Iphone SE 2gth

 
Hello everyone, I have a question. On iPhone iOS 16.4.1, it is allowing to take a screenshot. I wanted to know if this behavior is correct. I am using an iPhone SE 2nd generation device.

On Android, it doesn't allow taking a screenshot, properly blocking it. But on iOS, it allows it.

**Comment by robingenz** [comment]
Yes, this bevahior is correct. iOS does not offer a similar feature.
