### ISSUE TITLE
bug: iOS PrivacyScreen.disable() not working

### ISSUE THREAD

**Issue by benluria** [capacitor-community/privacy-screen#60]
**Plugin version:**

@capacitor-community/privacy-screen@4.1.0

**Platform(s):**

ios

**Current behavior:**

privacy screen is enabled by default. 
in app.component.ts, in platform.ready() handler:
```
PrivacyScreen.disable()
          .then(() => {
            console.log('privacy screen disabled');
          })
          .catch(err => console.error(err));
```
Screenshots are still blank.

**Expected behavior:**

after calling disable, screenshots would work normally.
after calling enable, they would stop.

**Steps to reproduce:**

put this in app.component.ts on ready:
```
PrivacyScreen.disable()
          .then(() => {
            console.log('privacy screen disabled');
          })
          .catch(err => console.error(err));

```
observe log in console that there was no error.
take a screenshot. its blank.

**Other information:**

**Capacitor doctor:**
Latest Dependencies:

  @capacitor/cli: 5.0.5
  @capacitor/core: 5.0.5
  @capacitor/android: 5.0.5
  @capacitor/ios: 5.0.5

Installed Dependencies:

  @capacitor/cli: 5.0.4
  @capacitor/android: 5.0.4
  @capacitor/core: 5.0.4
  @capacitor/ios: 5.0.4

[success] iOS looking great!

**Comment by robingenz** [comment]
Thank you for your request.
Please provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) using [this template](https://github.com/capawesome-team/.capacitor-app) in a public GitHub repository so I can debug the issue.

**Comment by dtarnawsky** [comment]
The default for the plugin is that the privacy screen is enabled.

If you want it disabled by default then open `capacitor.config.ts` and add:
```typescript
  plugins: {
    PrivacyScreen: {
      enable: false,
    },
  },
```

A sample application that does this is available at:
[https://github.com/dtarnawsky/cs-privacy-screen](https://github.com/dtarnawsky/cs-privacy-screen)
