### ISSUE TITLE
bug: When I change the screenOrientation in ios device with privacy screen enable the app crash

### ISSUE THREAD

**Issue by juanpadel** [capacitor-community/privacy-screen#61]
**Plugin version:**

    "@capacitor-community/privacy-screen": "^4.1.0",
    "@capacitor/android": "^5.0.5",
    "@capacitor/app": "5.0.3",
    "@capacitor/core": "^5.0.5",
    "@capacitor/haptics": "5.0.4",
    "@capacitor/ios": "5.0.5",
    "@capacitor/keyboard": "5.0.4",
    "@capacitor/status-bar": "5.0.4",
    "@fullcalendar/angular": "^6.0.3",
    "@fullcalendar/core": "^6.0.3",
    "@fullcalendar/daygrid": "^6.0.3",
    "@fullcalendar/interaction": "^6.0.3",
    "@fullcalendar/timegrid": "^6.0.3",
    "@ionic/angular": "^7.0.0",

**Platform(s):**

IOS

**Current behavior:**

The app crash when I change the screen orientation in ios because in android I don't have the problem, i want to know if this is a bug or the ios device can not change screen orientation with privacy screen enable

**Expected behavior:**

the app does not crash when I change orientation in ios

**Steps to reproduce:**

When I change the screen orientation the app crash in ios

**Related code:**

  constructor(
    private router: Router, 
    private route: ActivatedRoute,
    private platform: Platform
  ){
    this.platform.ready().then(() => {
      if (this.platform.is('android')) {
          this.enablePrivacyScreen(); 
      } else if (this.platform.is('ios')) {
          this.enablePrivacyScreen(); 
      } else {
           //fallback to browser APIs or
           console.log('The platform is not supported');
          }
      })
  }

  public async enablePrivacyScreen(): Promise<void> {
    await PrivacyScreen.enable();
  }
  
  public async disablePrivacyScreen(): Promise<void> {
    await PrivacyScreen.disable();
  }
```
insert short code snippets here
```

**Other information:**

**Capacitor doctor:**

```
insert the output from `npx cap doctor` here
```

**Comment by robingenz** [comment]
I could not reproduce the issue with the [demo app](https://github.com/robingenz/capacitor-plugin-demo).

![RPReplay_Final1687783876](https://github.com/capacitor-community/privacy-screen/assets/13857929/6757a79f-4b98-4534-8d66-f6a4ff1153e1)

**Comment by TripShade** [comment]
#62 Fixes this for me.
