### ISSUE TITLE
bug: this is not working It also prevents screenshots (a black screen will be captured) [ios]

### ISSUE THREAD

**Issue by hashemalkayal** [capacitor-community/privacy-screen#63]
**Plugin version:**
@capacitor-community/privacy-screen: "4.1.1"
@capacitor/core: "5.0.5",

**Platform(s):**
IOS

**Current behavior:**
when i try take screen shot from ios device is show my app screen instead black screen

**Expected behavior:**
black screen instead my app screen

**Steps to reproduce:**

**Related code:**

  const preventScreenshot = async (): void => {
    await PrivacyScreen.enable();
  };
  
  
   if (platform !== 'web') preventScreenshot();

```
insert short code snippets here
```

**Other information:**

**Capacitor doctor:**

```
insert the output from `npx cap doctor` here
```

**Comment by robingenz** [comment]
I cannot reproduce the issue using this [demo app](https://github.com/robingenz/capacitor-plugin-demo) on my iPhone 13 with iOS 16.5.1.
Please provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) using [this template](https://github.com/capawesome-team/.capacitor-app) in a public GitHub repository so I can debug the issue.

**Comment by hashemalkayal** [comment]
@robingenz  

i created new project and i faced the same issue as well

github :  https://github.com/hashemalkayal/demo-app-capacitor

**Comment by robingenz** [comment]
Just to make sure I didn't misunderstand you: The screenshot shows your app screen but you expect a black screen, right?

**Comment by hashemalkayal** [comment]
@robingenz 

Yes, sure. That's what I mean

**Comment by robingenz** [comment]
Sorry, i still can't reproduce your issue, see:

https://github.com/capacitor-community/privacy-screen/assets/13857929/60bc705d-aae1-4122-a091-e74b20461ee8

The screenshot is black.

**Comment by hashemalkayal** [comment]
@robingenz  

just when you call -- Privacy Screen.enable();

 see black screen no extra configurations on ios platform ?

**Comment by robingenz** [comment]
Yeah, I used your example app.

**Comment by hashemalkayal** [comment]
My iPhone 14 with iOS version 16.2 

on app switcher mode my screen is replaced with gray color (correct behvior)

but when i try take screenshot i can see my app screen (incorrect behavior)

**Comment by robingenz** [comment]
I understand that but I can't reproduce the problem and thus can't debug it.
You are welcome to debug it yourself and create a PR with a fix.
