### ISSUE TITLE
bug: Plugin does not work on ioS 17

### ISSUE THREAD

**Issue by renekroll** [capacitor-community/privacy-screen#74]
**Plugin version:**
v4.2.0

**Platform(s):**
iOS

**Current behavior:**
Thanks for the great plugin. We detected a problem after update to iOS 17
Screenshots can be taken on iOS 17.0.x

**Expected behavior:**
Screenshots can not be taken on iOS 17.0.x

**Steps to reproduce:**
take a screenshot under iOS 17

**Comment by robingenz** [comment]
Thank you! This issue is already known (see #73). I will take a closer look.
