### ISSUE TITLE
bug: Screen remains black after closing/opening app

### ISSUE THREAD

**Issue by reinventit** [capacitor-community/privacy-screen#78]
**Plugin version:**
4.2.1

**Platform(s):**
iOS (at least 16.4)

**Current behavior:**
When closing the app and re-opening, the screen remains black.

**Expected behavior:**
App should be renderend again

**Steps to reproduce:**
Open app, close app and re-open again

**Related code:**
It seems to be caused by the way modalPresentationStyle of the privacyViewController. It is currently set to 'overFullScreen' and this causes the underlaying view to be unloaded. If we change this to 'fullScreen' everything seems to be working.

Not working for me:
```
privacyViewController.modalPresentationStyle = UIModalPresentationStyle.overFullScreen
```
Working correctly for me:
```
privacyViewController.modalPresentationStyle = UIModalPresentationStyle.fullScreen
```

**Other information:**

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/cli: 5.5.1
  @capacitor/ios: 5.5.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by robingenz** [comment]
Hi, unfortunately I cannot reproduce your issue, see:

![Bildschirmaufnahme 2023-11-06 um 17 40 39](https://github.com/capacitor-community/privacy-screen/assets/13857929/9626d6ed-19ad-4589-ad03-4a2df19ecc1b)

**Comment by reinventit** [comment]
This seems to be different for iPhone / iPad. 

Indeed everything works fine on the iPhone, but when I try the same with the iPad simulator the problem exists. Can you try and see if you can reproduce the issue when simulating an iPad?

**Comment by robingenz** [comment]
Thanks, i can reproduce this issue with iPadOS 16.4.

**Comment by tobiloeb** [comment]
Hi,

maybe I am facing the same issue on MacOS. With Plugin Version >= 4.0.0 an Capacitor 5, I am not able to use the App on MacOS anymore. The App shows correctly at startup, but with the first click anywhere, the App becomes black.

Can you reproduce this as well?

Regards 
Tobias

**Comment by reinventit** [comment]
Hi Tobias,

Maybe you can try of my PR fixes your issue as well?

https://github.com/reinventit/privacy-screen/tree/fix-black-screen

Regards,
Rein

**Comment by robingenz** [comment]
Does the problem still exist with the latest version?
