### ISSUE TITLE
bug: disable method does not work on iOS

### ISSUE THREAD

**Issue by Phil0x11** [capacitor-community/privacy-screen#82]
**Plugin version:**
4.2.1

**Platform(s):**
iOS

**Current behavior:**
If I call the disable method the privacy screen will not be disabled in screenshots. I am still not able to screenshot the app.

**Expected behavior:**
After calling the disable method, the privacy screen will be disabled.

**Steps to reproduce:**
1. Clone example github repo
2. Build code on iOS device
3. Screenshot App --> Working
4. Click on "Enable Privacy Screen" --> Working (screenshot does not work)
5. Click on "Disable Privacy Screen" --> Not working (screenshot still does not work)

**Related code:**
https://github.com/Phil0x11/capacitor-privacy-screen-test

**Capacitor doctor:**
Latest Dependencies:

  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/android: 5.5.1
  @capacitor/ios: 5.5.1

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 5.5.1
  @capacitor/core: 5.5.1
  @capacitor/ios: 5.5.1

**Comment by robingenz** [comment]
Unfortunately there are several problems with the screenshot feature. I may revert it (see https://github.com/capacitor-community/privacy-screen/issues/76#issuecomment-1776551316). However, PRs are welcome.

**Comment by mfinity168** [comment]
I encountered the same problem. Can't use  disable().  
My install packages on capacitor js.

  "@capacitor-community/privacy-screen": "4.2.2",
  "@capacitor/android": "5.5.1",
  "@capacitor/cli": "5.5.1",
  "@capacitor/core": "5.5.1",
  "@capacitor/ios": "5.5.1",

please resolve problem

Thanks

**Comment by Phil0xFF** [comment]
I looked a little bit into that issue. It seems not all secure UITextField get removed on calling the `enableScreenshots` method. I did not yet found a way to fix that.

**Comment by jkyoutsey** [comment]
What would the effect of reverting your last change be? Would it just stop working all together, or...? I see the same issue that disable doesn't work on iOS and that's quite a blocker at this point.

**Comment by robingenz** [comment]
> What would the effect of reverting your last change be?

Screenshots would no longer be prevented under iOS.

**Comment by taitems** [comment]
I'd be happy with removing the prevention on iOS, I'm more interested in event capture. Or even if you forked the plugin?

**Comment by rogomez-pricesmart** [comment]
For some reason when the for of self.subviews, the items that are returned are not of type UITextField,
I have a small modification and it seems to work, first I declare a secureTextFields variable of type array, and then in the 
addSecureText function I make an append field to the variable, and then when the enableScreenshots function is called it cycles through the array and not self.subviews, I attach screen I hope to help thanks

<img width="808" alt="swift" src="https://github.com/capacitor-community/privacy-screen/assets/94871614/a7075b0f-d541-4631-a524-fb6bd9f57dfd">

**Comment by jonas-elias** [comment]
> For some reason when the for of self.subviews, the items that are returned are not of type UITextField, I have a small modification and it seems to work, first I declare a secureTextFields variable of type array, and then in the addSecureText function I make an append field to the variable, and then when the enableScreenshots function is called it cycles through the array and not self.subviews, I attach screen I hope to help thanks
> 
> <img alt="swift" width="808" src="https://private-user-images.githubusercontent.com/94871614/304897551-a7075b0f-d541-4631-a524-fb6bd9f57dfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NzY0MjUsIm5iZiI6MTcwOTY3NjEyNSwicGF0aCI6Ii85NDg3MTYxNC8zMDQ4OTc1NTEtYTcwNzViMGYtZDU0MS00NjMxLWE1MjQtZmI2YmQ5ZjU3ZGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDIyMDIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMDA0MTljZDZmZDBmZDk4YjliNTkxY2NiODg5N2IyOWFmNGQwZGIxZmNkNGU1MzJhZjQwMDUxOGEyMzY1ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BKbVPe50YMEuDyfp_GkIg7w90q2UTUT9Q3nUDvjFz-8">

It appears that the modification you made, where you declare a separate array secureTextFields to store the secure text fields and append to it in the addSecureText function, is causing a memory leak issue.

The reason for this memory leak is that when you append newField to secureTextFields, you're holding a strong reference to newField within the array. If you don't manage these references properly, it can lead to retain cycles, where objects reference each other and cannot be deallocated even when they are no longer needed.

To resolve this memory leak, you need to ensure that you properly manage the lifecycle of the UITextField instances stored in secureTextFields. This could involve removing references to them when they are no longer needed, such as when the corresponding view is removed from the superview or when the text fields themselves are deallocated.

Check pull request mention 😎🌷
