### ISSUE TITLE
bug: Webview not reactive on iOS after installation of the plugin from version 4.1.0

### ISSUE THREAD

**Issue by lhalleux** [capacitor-community/privacy-screen#84]
**Plugin version:**

All versions from 4.1.0 : 
- 4.1.0
- 4.2.0
- 4.2.1
- 4.22

**Platform(s):**

- iOS only 
- iOS 17.0.3 - Iphone 14 physical
- iOS 17.0.0 - Iphone 15 Pro Max simulator
- iOS 16.2 - Iphone 12 mini simulator

**Current behavior:**

When we use a version from 4.1.0, the webkit view is not reactive, all actions aren't intercepted. 

**Expected behavior:**

The webkit is reactive as it need to be

**Steps to reproduce:**
Install a version of the privacy capacitor-community/privacy-screen from 4.1.0. 
Build the application and run it on a physical device or simulated one. 
Now you cannot be able to interact with the webview.

**Related code:**

After some debuggin, it seems to be the code that breaks the reactivity of the webview kit :
```
DispatchQueue.main.async {
            self.bridge?.webView?.disableScreenshots()
        }
```

**Other information:**
None, do not hesitate to contact me if you need any specific informations.

**Capacitor doctor:**

```
Latest Dependencies:

  @capacitor/cli: unknown
  @capacitor/core: unknown
  @capacitor/android: unknown
  @capacitor/ios: unknown

Installed Dependencies:

  @capacitor/cli: 5.6.0
  @capacitor/core: 5.6.0
  @capacitor/android: 5.6.0
  @capacitor/ios: 5.6.0

[info] Using Gemfile: RubyGems bundle installed
[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by robingenz** [comment]
Unfortunately there are several problems with the screenshot feature. I plan to revert it (see https://github.com/capacitor-community/privacy-screen/issues/76#issuecomment-1776551316) with the next major release (which should be published this month).
