### ISSUE TITLE
bug: runtime error: `application tried to present modal view controller on itself`

### ISSUE THREAD

**Issue by tafelnl** [capacitor-community/privacy-screen#88]
**Plugin version:**
v4.2.3

**Platform(s):**
iOS

**Steps to reproduce:**
1. just keep the default config
2. swipe from the bottom so that the App Switcher opens
3. click on the app, so that it opens again
4. immediately and quickly (this is important) swipe up from the bottom so that the App Switcher opens
5. do this a few times until the said error occurs

I know this is not an ideal reproduction. But I cannot find a consistent/simple way to reproduce this instead. Mostly it happens after trying step 2,3,4 like 2-5 times though

**Comment by robingenz** [comment]
Does the problem still exist with the latest version?

**Comment by robingenz** [comment]
PRs are welcome.

**Comment by andrerds** [comment]
> Posso confirmar este problema - temos exatamente o mesmo problema. Após o downgrade para 4.2.2, as falhas desapareceram.
> 
> ![colidir](https://private-user-images.githubusercontent.com/7167030/323873237-0469a324-d7eb-4a28-a3c3-ea23cc3dcbe5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MDA5NTIsIm5iZiI6MTcxMzkwMDY1MiwicGF0aCI6Ii83MTY3MDMwLzMyMzg3MzIzNy0wNDY5YTMyNC1kN2ViLTRhMjgtYTNjMy1lYTIzY2MzZGNiZTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjNUMTkzMDUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDM5NjQ1MDA4ZWQwOGZkYjc0NGZlMzZiOTNhMjAzZjcyNDM5ZWQwN2I4ZWQ2OGFjYjFmNTNlYmEyZDM3MjZjZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JPB0OSXoxgbrlw8VW5jU7dGCb5NhPA8T9ujMDPcaGa0)

@micbis 
Hello friend, everything okay? I hope so. Can I ask a question? How do you know it's this plugin that caused the error? I'm also having this error in this topic, but I couldn't reach a conclusion that it was this problem. I'm just curious, but I'm dealing with the same problem.

**Comment by andrerds** [comment]
> > Posso confirmar este problema - temos exatamente o mesmo problema. Após o downgrade para 4.2.2, as falhas desapareceram.
> > ![colidir](https://private-user-images.githubusercontent.com/7167030/323873237-0469a324-d7eb-4a28-a3c3-ea23cc3dcbe5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MDA5NTIsIm5iZiI6MTcxMzkwMDY1MiwicGF0aCI6Ii83MTY3MDMwLzMyMzg3MzIzNy0wNDY5YTMyNC1kN2ViLTRhMjgtYTNjMy1lYTIzY2MzZGNiZTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjNUMTkzMDUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDM5NjQ1MDA4ZWQwOGZkYjc0NGZlMzZiOTNhMjAzZjcyNDM5ZWQwN2I4ZWQ2OGFjYjFmNTNlYmEyZDM3MjZjZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JPB0OSXoxgbrlw8VW5jU7dGCb5NhPA8T9ujMDPcaGa0)
> 
> @micbis Hello friend, everything okay? I hope so. Can I ask a question? How do you know it's this plugin that caused the error? I'm also having this error in this topic, but I couldn't reach a conclusion that it was this problem. I'm just curious, but I'm dealing with the same problem.

Friend, I asked because the errors that appear to me point directly to the plugin. See the image below.

![Captura de Tela 2024-04-24 às 09 22 27](https://github.com/capacitor-community/privacy-screen/assets/6690006/b008b853-51fe-4c88-802e-0c6bb92b2f58)

Other errors have a similar description but don't directly show which file. Look at the image below, it's quite similar to the shared error.

![Captura de Tela 2024-04-24 às 09 11 56](https://github.com/capacitor-community/privacy-screen/assets/6690006/6f72a350-a3ad-4c10-bcfc-88116f1fd619)

I'm not sure if both errors are related. Do you think they might be related?

Regarding the plugin, I'm still on version 4.0.0. I need to update. Another thing is that I couldn't replicate the problem. I see I have the logs, but I can't reproduce it, and even worse, I don't know the impact on the application—whether it crashes, freezes, or sets off fireworks, haha. 

Thank

**Comment by 7-plus-t** [comment]
I can confirm the crash is caused by the plugin. As far as I can tell, the plugin tries to display the `privacyViewController` multiple if `handleWillResignActiveNotification` is called multiple times by the OS.

**Comment by robingenz** [comment]
@7-plus-t Would you be willing to create a PR?

**Comment by 7-plus-t** [comment]
@robingenz done, see https://github.com/capacitor-community/privacy-screen/pull/93
