### ISSUE TITLE
Capacitor 3 Support

### ISSUE THREAD

**Issue by robingenz** [capacitor-community/privacy-screen#9]
Updating Capacitor to 3.0.  
Guide: https://capacitorjs.com/docs/v3/updating/plugins/3-0  
New plugin template: https://github.com/ionic-team/create-capacitor-plugin/tree/main/assets/plugin-template

**Comment by robingenz** [comment]
The guide is a work-in-progress.
Currently waiting for final release.

**Comment by mheumann** [comment]
Hey, everything seems to work great with Capacitor 3. There is just one thing missing in the documentation. You renamed the class to PrivacySrcreenPlugin so one now needs to change the import statement and also the registation:
```java
import com.getcapacitor.plugin.privacyscreen.PrivacyScreenPlugin;

public class MainActivity extends BridgeActivity {
  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    registerPlugin(PrivacyScreenPlugin.class);
  }
}
```

**Comment by robingenz** [comment]
Hi, as far as I know Capacitor 3 has "Android Plugin Auto-loading" ([see here](https://capacitorjs.com/blog/announcing-capacitor-3-0-beta#android-plugin-auto-loading)). So you don't have to register the plugin manually anymore.
This section in the `README.md` still refers to Capacitor 2, I will remove it soon.

**Comment by mheumann** [comment]
I didn't test without registering it, but I refer to this section in the upgrade guide: https://capacitorjs.com/docs/v3/updating/3-0#switch-to-automatic-android-plugin-loading

**Comment by robingenz** [comment]
Custom Plugins refers to plug-ins a user builds specifically for an app.
Plugins included in `package.json` are registered automatically by the Capacitor CLI.
I tested it again and it works.

**Comment by mheumann** [comment]
Ah ok thank you! And great work with the plugin!
