### ISSUE TITLE
bug: Latest version is not available in npm

### ISSUE THREAD

**Issue by smithasanehalli** [capacitor-community/privacy-screen#90]
**Plugin version:**
https://www.npmjs.com/package/@capacitor-community/privacy-screen/v/2.1.1

**Platform(s):**
iOS

**Current behavior:**
I am upgrading my project to capacitor 6 and couldn't resolve the dependencies because of below error

Could not resolve dependency:
npm ERR! peer @capacitor/core@"^3.0.0" from @capacitor-community/privacy-screen@2.1.1
npm ERR! node_modules/@capacitor-community/privacy-screen
npm ERR!   @capacitor-community/privacy-screen@"^2.1.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 

**Expected behavior:**
I can see that the plugin is updated to capacitor 6, is any reason why it isn't published to npm yet?

**Steps to reproduce:**
use privacy screen plugin with latest capacitor 6

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Capacitor doctor:**

```
insert the output from `npx cap doctor` here
```

**Comment by robingenz** [comment]
The latest version is published, see https://www.npmjs.com/package/@capacitor-community/privacy-screen/v/5.0.0.
