### ISSUE TITLE
Question: how can I set custom image?

### ISSUE THREAD

**Issue by Pierlu1586** [capacitor-community/privacy-screen#91]
Hi everyone!
I'm trying to add a custom image but I always see black screen when I take a screenshot on IOS device.
Currently I have my custom image in "myProject/ios/App/App/Assets.xcassets/Splash.imageset/customImage.png" and I have edited capacitor.config.json (path: myProject/ios/App/App/capacitor.config.json) with:

```
	"PrivacyScreen": {
			"enable": false,
			"useImageBackground": true,
			"imageName": "customImage"
		}
```
 

Some informations. 
I'm working on an angular/ionic project and I'm using capacitor-community/privacy-screen v.5.0.0
I change "enable" property in specific pages of my application.

Where am I doing wrong?
Any suggestions?

Thanks

**Comment by robingenz** [comment]
Here you can find an example on how to use the `imageName` configuration property: https://github.com/robingenz/capacitor-plugin-demo/tree/main

**Comment by Pierlu1586** [comment]
Thank you @robingenz for your answer.
I have created a new imageset folder for my custom image (with Contents.json e customImage.png) and I have changed capacitor.config.json.
Now I see my custom image in the upper-right corner but when I take screenshot I get black screen. :(



https://github.com/capacitor-community/privacy-screen/assets/52927087/83aa11b2-a99f-4e3e-878c-f68e30efe3a2

**Comment by robingenz** [comment]
Please provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) using [this template](https://github.com/capawesome-team/.capacitor-app) in a public GitHub repository so I can debug the issue.

**Comment by ZhipengZeng** [comment]
@robingenz  
The splash screen displays correctly when switching the app. Can we have a custom image for screenshot instead of a black screen?

**Comment by robingenz** [comment]
@ZhipengZeng Your request is not related to this issue. Please create a separate feature request.
