### ISSUE TITLE
feat: Custom Image for Screenshot

### ISSUE THREAD

**Issue by ZhipengZeng** [capacitor-community/privacy-screen#99]
**Is your feature request related to a problem? Please describe:**

A self defined image for switch app screen is well done. 
But for screenshot it uses a black screen instead, which is kind of not that user friendly.

**Describe the solution you'd like:**

A separate custom image(optional) for screenshot defined in capacitor.config.ts

`
    PrivacyScreen: {
      enable: true,
      imageName: "Splash",
      screenshotImageName: "CustomScreenshotImage"
    }
`

**Comment by robingenz** [comment]
I suggest we use the `imageName` option for both. Feel free to create a PR.

**Comment by ZhipengZeng** [comment]
I did some research and it seems we don't have many options to implement screenshot blocker for iOS. The UITextField isSecureTextEntry approach is the only effective one.

**Comment by robingenz** [comment]
You're right. I totally forgot that. Since there is no other solution, I close this issue as not planned.
